/**
 * Auto-generated IDL type for the credit_vault program.
 * In production, this is generated by `anchor build` and placed in target/idl/.
 * For the hackathon demo, we define it manually for frontend integration.
 */

export type CreditVault = {
  version: "0.1.0";
  name: "credit_vault";
  address: string;
  instructions: [
    {
      name: "initializeProtocol";
      accounts: [
        { name: "protocolConfig"; isMut: true; isSigner: false },
        { name: "admin"; isMut: true; isSigner: true },
        { name: "systemProgram"; isMut: false; isSigner: false }
      ];
      args: [
        { name: "lenderProfitShareBps"; type: "u16" },
        { name: "minCollateralRatioBps"; type: "u16" },
        { name: "liquidationThresholdBps"; type: "u16" },
        { name: "minCreditScore"; type: "u8" }
      ];
    },
    {
      name: "initializeVault";
      accounts: [
        { name: "vault"; isMut: true; isSigner: false },
        { name: "vaultAuthority"; isMut: false; isSigner: false },
        { name: "protocolConfig"; isMut: false; isSigner: false },
        { name: "borrower"; isMut: true; isSigner: true },
        { name: "borrowerTokenAccount"; isMut: true; isSigner: false },
        { name: "vaultTokenAccount"; isMut: true; isSigner: false },
        { name: "usdcMint"; isMut: false; isSigner: false },
        { name: "tokenProgram"; isMut: false; isSigner: false },
        { name: "systemProgram"; isMut: false; isSigner: false }
      ];
      args: [
        { name: "loanAmount"; type: "u64" },
        { name: "collateralAmount"; type: "u64" },
        { name: "creditScore"; type: "u8" },
        { name: "riskLevel"; type: { defined: { name: "RiskLevel" } } },
        { name: "zkProofHash"; type: "string" },
        { name: "collateralRatioBps"; type: "u16" }
      ];
    },
    {
      name: "fundVault";
      accounts: [
        { name: "vault"; isMut: true; isSigner: false },
        { name: "lender"; isMut: true; isSigner: true },
        { name: "lenderTokenAccount"; isMut: true; isSigner: false },
        { name: "vaultTokenAccount"; isMut: true; isSigner: false },
        { name: "tokenProgram"; isMut: false; isSigner: false }
      ];
      args: [];
    },
    {
      name: "simulateYield";
      accounts: [
        { name: "vault"; isMut: true; isSigner: false },
        { name: "protocolConfig"; isMut: false; isSigner: false },
        { name: "authority"; isMut: false; isSigner: true }
      ];
      args: [{ name: "pnlAmount"; type: "i64" }];
    },
    {
      name: "liquidate";
      accounts: [
        { name: "vault"; isMut: true; isSigner: false },
        { name: "vaultAuthority"; isMut: false; isSigner: false },
        { name: "vaultTokenAccount"; isMut: true; isSigner: false },
        { name: "lenderTokenAccount"; isMut: true; isSigner: false },
        { name: "tokenProgram"; isMut: false; isSigner: false },
        { name: "authority"; isMut: false; isSigner: true }
      ];
      args: [];
    },
    {
      name: "withdraw";
      accounts: [
        { name: "vault"; isMut: true; isSigner: false },
        { name: "vaultAuthority"; isMut: false; isSigner: false },
        { name: "borrower"; isMut: true; isSigner: true },
        { name: "vaultTokenAccount"; isMut: true; isSigner: false },
        { name: "borrowerTokenAccount"; isMut: true; isSigner: false },
        { name: "lenderTokenAccount"; isMut: true; isSigner: false },
        { name: "tokenProgram"; isMut: false; isSigner: false }
      ];
      args: [];
    },
    {
      name: "closeVault";
      accounts: [
        { name: "vault"; isMut: true; isSigner: false },
        { name: "borrower"; isMut: true; isSigner: true }
      ];
      args: [];
    }
  ];
  accounts: [
    {
      name: "CreditVault";
      discriminator: number[];
      type: {
        kind: "struct";
        fields: [
          { name: "bump"; type: "u8" },
          { name: "borrower"; type: "pubkey" },
          { name: "lender"; type: "pubkey" },
          { name: "loanAmount"; type: "u64" },
          { name: "collateralAmount"; type: "u64" },
          { name: "currentCollateral"; type: "u64" },
          { name: "interestDue"; type: "u64" },
          { name: "lenderProfitLocked"; type: "u64" },
          { name: "strategyReinvestPool"; type: "u64" },
          { name: "vaultNav"; type: "u64" },
          { name: "creditScore"; type: "u8" },
          { name: "riskLevel"; type: { defined: { name: "RiskLevel" } } },
          { name: "approved"; type: "bool" },
          { name: "status"; type: { defined: { name: "VaultStatus" } } },
          { name: "zkProofHash"; type: "string" },
          { name: "collateralRatioBps"; type: "u16" },
          { name: "createdAt"; type: "i64" },
          { name: "lastYieldAt"; type: "i64" },
          { name: "cumulativePnl"; type: "i64" },
          { name: "yieldRounds"; type: "u16" }
        ];
      };
    },
    {
      name: "ProtocolConfig";
      discriminator: number[];
      type: {
        kind: "struct";
        fields: [
          { name: "admin"; type: "pubkey" },
          { name: "lenderProfitShareBps"; type: "u16" },
          { name: "minCollateralRatioBps"; type: "u16" },
          { name: "liquidationThresholdBps"; type: "u16" },
          { name: "minCreditScore"; type: "u8" },
          { name: "bump"; type: "u8" }
        ];
      };
    }
  ];
  types: [
    {
      name: "CreditVault";
      type: {
        kind: "struct";
        fields: [
          { name: "bump"; type: "u8" },
          { name: "borrower"; type: "pubkey" },
          { name: "lender"; type: "pubkey" },
          { name: "loanAmount"; type: "u64" },
          { name: "collateralAmount"; type: "u64" },
          { name: "currentCollateral"; type: "u64" },
          { name: "interestDue"; type: "u64" },
          { name: "lenderProfitLocked"; type: "u64" },
          { name: "strategyReinvestPool"; type: "u64" },
          { name: "vaultNav"; type: "u64" },
          { name: "creditScore"; type: "u8" },
          { name: "riskLevel"; type: { defined: { name: "RiskLevel" } } },
          { name: "approved"; type: "bool" },
          { name: "status"; type: { defined: { name: "VaultStatus" } } },
          { name: "zkProofHash"; type: "string" },
          { name: "collateralRatioBps"; type: "u16" },
          { name: "createdAt"; type: "i64" },
          { name: "lastYieldAt"; type: "i64" },
          { name: "cumulativePnl"; type: "i64" },
          { name: "yieldRounds"; type: "u16" }
        ];
      };
    },
    {
      name: "ProtocolConfig";
      type: {
        kind: "struct";
        fields: [
          { name: "admin"; type: "pubkey" },
          { name: "lenderProfitShareBps"; type: "u16" },
          { name: "minCollateralRatioBps"; type: "u16" },
          { name: "liquidationThresholdBps"; type: "u16" },
          { name: "minCreditScore"; type: "u8" },
          { name: "bump"; type: "u8" }
        ];
      };
    },
    {
      name: "RiskLevel";
      type: {
        kind: "enum";
        variants: [
          { name: "VeryLow" },
          { name: "Low" },
          { name: "Medium" },
          { name: "Elevated" },
          { name: "High" },
          { name: "Liquidation" }
        ];
      };
    },
    {
      name: "VaultStatus";
      type: {
        kind: "enum";
        variants: [
          { name: "Pending" },
          { name: "Funded" },
          { name: "Strategy" },
          { name: "Loss" },
          { name: "Liquidated" },
          { name: "Repaid" },
          { name: "Withdrawn" }
        ];
      };
    }
  ];
  errors: [
    { code: 6000; name: "InsufficientCollateralRatio"; msg: "Collateral ratio is below the minimum required threshold" },
    { code: 6001; name: "CreditScoreTooLow"; msg: "Credit score is below the minimum required for approval" },
    { code: 6002; name: "LoanNotApproved"; msg: "Loan was not approved by AI/ZK risk assessment" },
    { code: 6003; name: "InvalidVaultStatus"; msg: "Vault is not in the correct status for this operation" },
    { code: 6004; name: "UnauthorizedBorrower"; msg: "Only the borrower can perform this action" },
    { code: 6005; name: "UnauthorizedLender"; msg: "Only the lender can perform this action" },
    { code: 6006; name: "UnauthorizedAdmin"; msg: "Only the admin can perform this action" },
    { code: 6007; name: "VaultLiquidated"; msg: "Vault has been liquidated, no further operations allowed" },
    { code: 6008; name: "LoanNotRepaid"; msg: "Loan has not been fully repaid yet" },
    { code: 6009; name: "MathOverflow"; msg: "Arithmetic overflow occurred" },
    { code: 6010; name: "LiquidationTriggered"; msg: "Collateral ratio fell below liquidation threshold" },
    { code: 6011; name: "InvalidPnlAmount"; msg: "Invalid profit/loss amount" },
    { code: 6012; name: "AlreadyFunded"; msg: "Vault is already funded" },
    { code: 6013; name: "MissingZkProofHash"; msg: "ZK proof hash is required for vault initialization" }
  ];
};

export const IDL: CreditVault = {
  version: "0.1.0",
  name: "credit_vault",
  address: "4QP9SXSrW7pqaJqFFj9y5MWYfZ62dHMvpWLrZ7wmYMvZ",
  instructions: [
    {
      name: "initializeProtocol",
      accounts: [
        { name: "protocolConfig", isMut: true, isSigner: false },
        { name: "admin", isMut: true, isSigner: true },
        { name: "systemProgram", isMut: false, isSigner: false }
      ],
      args: [
        { name: "lenderProfitShareBps", type: "u16" },
        { name: "minCollateralRatioBps", type: "u16" },
        { name: "liquidationThresholdBps", type: "u16" },
        { name: "minCreditScore", type: "u8" }
      ]
    },
    {
      name: "initializeVault",
      accounts: [
        { name: "vault", isMut: true, isSigner: false },
        { name: "vaultAuthority", isMut: false, isSigner: false },
        { name: "protocolConfig", isMut: false, isSigner: false },
        { name: "borrower", isMut: true, isSigner: true },
        { name: "borrowerTokenAccount", isMut: true, isSigner: false },
        { name: "vaultTokenAccount", isMut: true, isSigner: false },
        { name: "usdcMint", isMut: false, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false }
      ],
      args: [
        { name: "loanAmount", type: "u64" },
        { name: "collateralAmount", type: "u64" },
        { name: "creditScore", type: "u8" },
        { name: "riskLevel", type: { defined: { name: "RiskLevel" } } },
        { name: "zkProofHash", type: "string" },
        { name: "collateralRatioBps", type: "u16" }
      ]
    },
    {
      name: "fundVault",
      accounts: [
        { name: "vault", isMut: true, isSigner: false },
        { name: "lender", isMut: true, isSigner: true },
        { name: "lenderTokenAccount", isMut: true, isSigner: false },
        { name: "vaultTokenAccount", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false }
      ],
      args: []
    },
    {
      name: "simulateYield",
      accounts: [
        { name: "vault", isMut: true, isSigner: false },
        { name: "protocolConfig", isMut: false, isSigner: false },
        { name: "authority", isMut: false, isSigner: true }
      ],
      args: [{ name: "pnlAmount", type: "i64" }]
    },
    {
      name: "liquidate",
      accounts: [
        { name: "vault", isMut: true, isSigner: false },
        { name: "vaultAuthority", isMut: false, isSigner: false },
        { name: "vaultTokenAccount", isMut: true, isSigner: false },
        { name: "lenderTokenAccount", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "authority", isMut: false, isSigner: true }
      ],
      args: []
    },
    {
      name: "withdraw",
      accounts: [
        { name: "vault", isMut: true, isSigner: false },
        { name: "vaultAuthority", isMut: false, isSigner: false },
        { name: "borrower", isMut: true, isSigner: true },
        { name: "vaultTokenAccount", isMut: true, isSigner: false },
        { name: "borrowerTokenAccount", isMut: true, isSigner: false },
        { name: "lenderTokenAccount", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false }
      ],
      args: []
    },
    {
      name: "closeVault",
      accounts: [
        { name: "vault", isMut: true, isSigner: false },
        { name: "borrower", isMut: true, isSigner: true }
      ],
      args: []
    }
  ],
  accounts: [
    {
      name: "CreditVault",
      discriminator: [143,180,135,248,84,85,183,70],
      type: {
        kind: "struct",
        fields: [
          { name: "bump", type: "u8" },
          { name: "borrower", type: "pubkey" },
          { name: "lender", type: "pubkey" },
          { name: "loanAmount", type: "u64" },
          { name: "collateralAmount", type: "u64" },
          { name: "currentCollateral", type: "u64" },
          { name: "interestDue", type: "u64" },
          { name: "lenderProfitLocked", type: "u64" },
          { name: "strategyReinvestPool", type: "u64" },
          { name: "vaultNav", type: "u64" },
          { name: "creditScore", type: "u8" },
          { name: "riskLevel", type: { defined: { name: "RiskLevel" } } },
          { name: "approved", type: "bool" },
          { name: "status", type: { defined: { name: "VaultStatus" } } },
          { name: "zkProofHash", type: "string" },
          { name: "collateralRatioBps", type: "u16" },
          { name: "createdAt", type: "i64" },
          { name: "lastYieldAt", type: "i64" },
          { name: "cumulativePnl", type: "i64" },
          { name: "yieldRounds", type: "u16" }
        ]
      }
    },
    {
      name: "ProtocolConfig",
      discriminator: [207,91,250,28,152,179,215,209],
      type: {
        kind: "struct",
        fields: [
          { name: "admin", type: "pubkey" },
          { name: "lenderProfitShareBps", type: "u16" },
          { name: "minCollateralRatioBps", type: "u16" },
          { name: "liquidationThresholdBps", type: "u16" },
          { name: "minCreditScore", type: "u8" },
          { name: "bump", type: "u8" }
        ]
      }
    }
  ],
  types: [
    {
      name: "CreditVault",
      type: {
        kind: "struct",
        fields: [
          { name: "bump", type: "u8" },
          { name: "borrower", type: "pubkey" },
          { name: "lender", type: "pubkey" },
          { name: "loanAmount", type: "u64" },
          { name: "collateralAmount", type: "u64" },
          { name: "currentCollateral", type: "u64" },
          { name: "interestDue", type: "u64" },
          { name: "lenderProfitLocked", type: "u64" },
          { name: "strategyReinvestPool", type: "u64" },
          { name: "vaultNav", type: "u64" },
          { name: "creditScore", type: "u8" },
          { name: "riskLevel", type: { defined: { name: "RiskLevel" } } },
          { name: "approved", type: "bool" },
          { name: "status", type: { defined: { name: "VaultStatus" } } },
          { name: "zkProofHash", type: "string" },
          { name: "collateralRatioBps", type: "u16" },
          { name: "createdAt", type: "i64" },
          { name: "lastYieldAt", type: "i64" },
          { name: "cumulativePnl", type: "i64" },
          { name: "yieldRounds", type: "u16" }
        ]
      }
    },
    {
      name: "ProtocolConfig",
      type: {
        kind: "struct",
        fields: [
          { name: "admin", type: "pubkey" },
          { name: "lenderProfitShareBps", type: "u16" },
          { name: "minCollateralRatioBps", type: "u16" },
          { name: "liquidationThresholdBps", type: "u16" },
          { name: "minCreditScore", type: "u8" },
          { name: "bump", type: "u8" }
        ]
      }
    },
    {
      name: "RiskLevel",
      type: {
        kind: "enum",
        variants: [
          { name: "VeryLow" },
          { name: "Low" },
          { name: "Medium" },
          { name: "Elevated" },
          { name: "High" },
          { name: "Liquidation" }
        ]
      }
    },
    {
      name: "VaultStatus",
      type: {
        kind: "enum",
        variants: [
          { name: "Pending" },
          { name: "Funded" },
          { name: "Strategy" },
          { name: "Loss" },
          { name: "Liquidated" },
          { name: "Repaid" },
          { name: "Withdrawn" }
        ]
      }
    }
  ],
  errors: [
    { code: 6000, name: "InsufficientCollateralRatio", msg: "Collateral ratio is below the minimum required threshold" },
    { code: 6001, name: "CreditScoreTooLow", msg: "Credit score is below the minimum required for approval" },
    { code: 6002, name: "LoanNotApproved", msg: "Loan was not approved by AI/ZK risk assessment" },
    { code: 6003, name: "InvalidVaultStatus", msg: "Vault is not in the correct status for this operation" },
    { code: 6004, name: "UnauthorizedBorrower", msg: "Only the borrower can perform this action" },
    { code: 6005, name: "UnauthorizedLender", msg: "Only the lender can perform this action" },
    { code: 6006, name: "UnauthorizedAdmin", msg: "Only the admin can perform this action" },
    { code: 6007, name: "VaultLiquidated", msg: "Vault has been liquidated, no further operations allowed" },
    { code: 6008, name: "LoanNotRepaid", msg: "Loan has not been fully repaid yet" },
    { code: 6009, name: "MathOverflow", msg: "Arithmetic overflow occurred" },
    { code: 6010, name: "LiquidationTriggered", msg: "Collateral ratio fell below liquidation threshold" },
    { code: 6011, name: "InvalidPnlAmount", msg: "Invalid profit/loss amount" },
    { code: 6012, name: "AlreadyFunded", msg: "Vault is already funded" },
    { code: 6013, name: "MissingZkProofHash", msg: "ZK proof hash is required for vault initialization" }
  ]
};

export const PROGRAM_ID = "4QP9SXSrW7pqaJqFFj9y5MWYfZ62dHMvpWLrZ7wmYMvZ";
